default_platform(:ios)

platform :ios do
  desc "Upload App Store screenshots only"
  lane :upload_screenshots do
    deliver(
      app_identifier: "com.mixandmatch.preferans",
      screenshots_path: "./fastlane/screenshots",
      skip_binary_upload: true,
      skip_metadata: true,
      overwrite_screenshots: true,
      submit_for_review: false
    )
  end
end

